#!/bin/bash

$HOME_PATH="/home/rootkit/Zone51/SaveSystem"

FLAG_PATH="$HOME_PATH/Flags"
LISTED_INCREMENTAL_PATH="$HOME_PATH/Lists.d"
EXPORT_PATH="$HOME_PATH/Data_Export"
EXPORT_CKSUM_PATH="$HOME_PATH/CkSum_Export"
SAVE_LIST_PATH="$HOME_PATH/ListSave.d"
EXCLUDE_LIST_PATH="$HOME_PATH/ExcludeSave.d"
SAVE_STATE_PATH="$HOME_PATH/Etats"
LOG_PATH="$HOME_PATH/Logs.d"
